fieldLayouts:
  c262fb6e-a538-4588-94cd-cfdbc116d2b3:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 04e11f53-1520-477d-95be-3f172dcb5738
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: dbfae31d-6a88-47e4-a7e5-23b4976e1377 # bannerImage
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c13b6c85-81da-4d84-b46c-b2ab1eb1517b
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 461c2288-72cc-4f7a-bac4-dc96a43ce01f # song
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e28d4576-2c67-480b-bc59-e8db0134f3c1
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 0fffebe7-0867-41ee-b0b6-ba125e41a14b
        userCondition: null
handle: default
hasTitleField: true
name: Default
section: 5719791e-e948-4303-b060-8671d8aca058 # New
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
