fieldLayouts:
  cceb4ea4-3125-4e7e-80f6-96bb968f64af:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 67b29399-ea93-4b19-b36a-ae8b25700d37
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 5311e559-394d-4e8d-94f2-b9da28794560 # Album
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: bdbeb34c-295a-4b38-90db-3a7cbe6d58cb
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 333e84b6-3acc-4085-9523-8d4201b1e272 # Artist
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 896b96ca-ea20-48b5-8cdb-f2c9815edb41
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 2c7b97f9-025f-4d92-bc09-12e676d46ee6 # New
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 467b30ab-426c-442e-9661-500e47c3d4af
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 11031fd5-cbc8-43b5-9bc7-8b399a1b6c8c # duration
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: dc205f82-5e53-4bae-b719-de4012e14ae6
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: dbfae31d-6a88-47e4-a7e5-23b4976e1377 # bannerImage
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 645cb8a2-c59b-4891-b716-539f71e1e5d5
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: c862b062-b584-4859-b69d-f911004602e1 # lyrics
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4a552856-db51-42cc-8c9b-29395e1c29f6
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 1c1a5d81-6138-4d0d-90cc-c106b037ca4a # genre
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e258e190-e118-41f8-b47e-1b84071eaf1e
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: e66ba489-239f-4fc6-acea-d723aa129c65 # videoclip
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 43dc5ef2-2539-46d5-8d3e-9f701a5828ea
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 83fa95cd-ecc7-4646-af09-0bce7b1269c4
        userCondition: null
handle: default
hasTitleField: true
name: Default
section: 1732db7e-48de-4cf2-9bb7-3acac5fb9573 # Song
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
