fieldLayouts:
  5d78d5fb-fa5f-40b0-99ac-39717c7bfaa2:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: f7f9f649-33d1-4cc3-ba06-bb14c70b2a3e
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 333e84b6-3acc-4085-9523-8d4201b1e272 # Artist
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: deef9235-b261-42df-82fc-52db8b0805b3
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 79353fa9-884d-4ed5-9f3b-6a87701ccee8 # Song
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ff635998-58f8-4fd6-a1f5-d584af062b34
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: ee9cf4ef-3bcb-40b2-9c2a-d7ba66b661c4 # release
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6254464e-e4a8-48db-bc37-15857cd1225e
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: dbfae31d-6a88-47e4-a7e5-23b4976e1377 # bannerImage
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 026e806e-46f9-4996-a08f-1ab0e69b993e
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 7d31c5e7-d10b-44e9-a833-d49e1fee5d1f
        userCondition: null
handle: default
hasTitleField: true
name: Default
section: 4b5394d6-2042-4375-9992-a2143c41d76c # Album
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
