columnSuffix: bsmjwvbz
contentColumnType: text
fieldGroup: 2266e771-fff7-4ddc-9312-203b8dea6017 # Common
handle: cat2
instructions: null
name: Cat2
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: false
  columnType: null
  initialRows: 4
  multiline: false
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
