columnSuffix: whweubsi
contentColumnType: string(6)
fieldGroup: 2266e771-fff7-4ddc-9312-203b8dea6017 # Common
handle: genre
instructions: null
name: genre
searchable: false
settings:
  columnType: null
  options:
    -
      __assoc__:
        -
          - label
          - Rock
        -
          - value
          - rock
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - Pop
        -
          - value
          - pop
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - Techno
        -
          - value
          - techno
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Dropdown
