dateModified: 1704345375
email:
  fromEmail: weshmusic@gmail.com
  fromName: weshmusic
  transportType: craft\mail\transportadapters\Sendmail
fs:
  assets:
    hasUrls: true
    name: assets
    settings:
      path: '@webroot'
    type: craft\fs\Local
    url: '@web'
meta:
  __names__:
    1c1a5d81-6138-4d0d-90cc-c106b037ca4a: genre # genre
    2c7b97f9-025f-4d92-bc09-12e676d46ee6: New # New
    3c8601ab-dd57-400e-8cf8-d48d90707958: $ALLOW_ADMIN_CHANGES # $ALLOW_ADMIN_CHANGES
    3ef8b120-80e0-43f2-a45f-a26d01567382: clickImage # clickImage
    4b5394d6-2042-4375-9992-a2143c41d76c: Album # Album
    5cf994e1-5ae5-4c05-ba71-b26aa0dc0230: Default # Default
    7e95d83a-0e02-4c1e-a67f-7e80d418f84c: music-assets # music-assets
    8a576cb0-ab59-4f0c-a154-9ef40473ae9d: Default # Default
    8dbaac6d-9024-4ed9-bf34-586b702b75b1: Footer # Footer
    8e1bdad0-912d-4aa1-9af9-8f8767edaa01: Default # Default
    51c5e28f-16de-46ac-a319-4cf205ceb250: clickImage # clickImage
    69b694fc-5ba6-431c-a5a2-7e26915e67a3: Default # Default
    76cd8eda-04cb-4fbe-b6c3-d29970a98d7b: Footertext # Footertext
    91ae1e85-45cd-4003-90bf-450ed64b47ba: Dialog # Dialog
    319dab0a-9518-4244-9c52-ea4fe4af5e99: Artist # Artist
    333e84b6-3acc-4085-9523-8d4201b1e272: Artist # Artist
    521d5b59-7b1c-46e7-93d6-b77f0f8fb7c7: nationality # nationality
    630c1328-1ec7-4b2f-a906-d3bf5ae94525: Default # Default
    00826af6-4c36-4085-a8bd-9cee32020e14: bannerImage # bannerImage
    1732db7e-48de-4cf2-9bb7-3acac5fb9573: Song # Song
    2266e771-fff7-4ddc-9312-203b8dea6017: Common # Common
    5311e559-394d-4e8d-94f2-b9da28794560: Album # Album
    8615e937-beb4-45a0-b4b8-79b483a3f8f4: Nederlands # Nederlands
    11031fd5-cbc8-43b5-9bc7-8b399a1b6c8c: duration # duration
    79353fa9-884d-4ed5-9f3b-6a87701ccee8: Song # Song
    80652ae7-dc2f-4584-a077-73d789627636: weshmusic # weshmusic
    5719791e-e948-4303-b060-8671d8aca058: New # New
    c19c22a7-9f04-46d9-ac9e-b34f35f6d425: weshmusic # weshmusic
    c862b062-b584-4859-b69d-f911004602e1: lyrics # lyrics
    dbfae31d-6a88-47e4-a7e5-23b4976e1377: bannerImage # bannerImage
    e66ba489-239f-4fc6-acea-d723aa129c65: videoclip # videoclip
    ee9cf4ef-3bcb-40b2-9c2a-d7ba66b661c4: release # release
plugins:
  abm-translationhelper:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
    settings:
      selectedSiteGroups:
        1:
          1: '0'
  cookie-consent-banner:
    edition: standard
    enabled: true
    schemaVersion: 1.0.1
    settings:
      allow: 'Allow cookies'
      async_js: ''
      auto_inject: '1'
      decline: Decline
      defer_js: ''
      disable_in_live_preview: ''
      dismiss: 'Got it!'
      dismiss_on_scroll: '0'
      dismiss_on_timeout: '0'
      excluded_categories: null
      excluded_entry_types: null
      expiry_days: '365'
      honour_do_not_track_header: ''
      layout: block
      learn: 'Learn More'
      learn_more_link: 'http://cookiesandyou.com/'
      message: 'This website uses cookies to ensure you get the best experience on our website.'
      palette: default
      palette_banner: '000000'
      palette_banner_text: ffffff
      palette_button: f1d600
      palette_button_text: '000000'
      palette_left_button_bg: f8e71c
      palette_left_button_text: '000000'
      palette_link: ffffff
      position: bottom
      preload_css: ''
      revokable: ''
      secure_only: ''
      target: _blank
      type: info
  element-api:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  instagramfeed:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
    settings:
      dump: false
      instagramUser: mnmbe
      proxyKey: ''
      subpath: ''
      timeout: 10
      useProxy: false
      useVolume: false
      volume: musicAssets
  ss-twitter-feed:
    edition: standard
    enabled: true
    schemaVersion: 1.0.9
    settings:
      access_token: MNMbe
      access_token_secret: MNMbe
      api_key: ''
      api_secret_key: ''
  tinymce:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  translator:
    edition: standard
    enabled: true
    schemaVersion: 0.1.0
  tweetfeed:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
    settings:
      apiKey: 84llCSKWgnTBFWP2A8suBpvRj
      apiKeySecret: 16YyQbQlbHvSR8ad4g0DRYugpxg37Uq0mpzRItmZsv5OcrdB28
      token: 1742743378779938817-ZaBRxdSm5KT95NjfDlMe9VmW2iSIrb
      tokenSecret: rnESGlNcT8HZBb9P5UisB5hM7YF3f2MoHB3Efn3MMFxxP
      userId: '19451065'
  whatsrabbit-live-chat:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
system:
  edition: solo
  live: true
  name: weshmusic
  schemaVersion: 4.5.3.0
  timeZone: America/Los_Angeles
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  requireEmailVerification: true
