defaultPlacement: end
enableVersioning: true
handle: album
name: Album
propagationMethod: all
siteSettings:
  80652ae7-dc2f-4584-a077-73d789627636: # weshmusic
    enabledByDefault: true
    hasUrls: true
    template: album/_entry
    uriFormat: 'album/{slug}'
type: channel
