defaultPlacement: end
enableVersioning: true
handle: artist
name: Artist
propagationMethod: all
siteSettings:
  80652ae7-dc2f-4584-a077-73d789627636: # weshmusic
    enabledByDefault: true
    hasUrls: true
    template: artist/_entry
    uriFormat: 'artist/{slug}'
type: channel
